### ISSUE TITLE
[Refatoração][Layout] Refatorar estilos idênticos, para reaproveitar código.

### ISSUE THREAD

**Issue by dev-cristhian** [GiullianoBGA/PlanningPoker#1]
O princípio DRY, 'Não se Repita', é um importante princípio que procura reduzir a duplicação de código e os problemas oriundos dessa prática.
A definição formal desse princípio diz :
"Cada parte do conhecimento deve ter uma representação única, não ambígua e definitiva dentro do sistema."
Extraindo o cerne do princípio : 'Não escreva código duplicado'  (embora o princípio seja mais que isso)
<br/>
Baseado no descrito acima, refatore o arquivo **app.css** e remova a repetição de estilo idêntico.
<br/>
Commit: https://github.com/GiullianoBGA/PlanningPoker/commit/c37660626b0fa07ba2d371a6991d9252d1fe0670
<br/>
<br/>
![image](https://user-images.githubusercontent.com/70783719/214749830-6e165f8f-a907-43ea-acbc-f131ab532beb.png)

**Comment by nathanaelf28** [comment]
Resolved in link: https://github.com/GiullianoBGA/PlanningPoker/pull/4
