### ISSUE TITLE
[Bug][Layout] Ao aplicar zoom na tela, os espaços entre as labels e os inputs quebram

### ISSUE THREAD

**Issue by dev-cristhian** [GiullianoBGA/PlanningPoker#2]
![image](https://user-images.githubusercontent.com/70783719/214751112-bf4c2ac4-96ae-49d3-bb7b-91df09efa47e.png)
<br/>
Baseado na imagem acima, podemos observar que foi definido um tamanho fixo em pixel para o espaço entre as labels e os inputs.
<br/>
Todavia, quando é aplicado zoom na tela, os espaços quebram o layout.
<br/>
![image](https://user-images.githubusercontent.com/70783719/214751306-141f1153-3626-4c22-9f60-d776925f4938.png)
<br/>
Gentileza corrigir o problema.
<br/>
<br/>
Material de apoio
https://www.youtube.com/watch?v=gOMK_xruAqc

**Comment by nathanaelf28** [comment]
Resolved in link: https://github.com/GiullianoBGA/PlanningPoker/pull/6
